name: mpox_env
channels:
    - conda-forge
    - bioconda
dependencies:
    - samtools=1.10
    - vcftools=0.1.16
    - minimap2=2.24
    - pandas=1.3.5
    - gofasta=1.2.1
    - pysam=0.20.0
    - python=3.7.12
    - fastp=0.23.2
    - seqkit=2.5.1